apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssom-metric-proxy
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssom-metric-proxy
  template:
    metadata:
      labels:
        app: ssom-metric-proxy
    spec:
      containers:
      - name: ssom-metric-proxy
        image: <your-docker-image>
        ports:
        - containerPort: 8000
        env:
        - name: TARGET_WEBHOOK_URL
          value: "http://aaaa,http://bbbb"
          # 콤마(,)로 구분해서 여러 URL에 웹훅 가능