apiVersion: v1
kind: Service
metadata:
  name: ssom-metric-proxy
  namespace: monitoring
spec:
  selector:
    app: ssom-metric-proxy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  